### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by billywatsy** [dallmann-consulting/OCPP.Core#11]
l have cloned the project fine, 

if l use the simulator and request connection, it always fails, debugging the code l have seen that it requires a basic auth token ( username and password ). l have done the steps of setting the charge point via the management : OCPP.Core.Management

The question is more on the simulator on why it's not sending the token in the header or where is it set on the simulator, l have used the latest in your git. or l am doing something wrong 

![image](https://user-images.githubusercontent.com/22769210/163346515-0f32469d-062a-43e2-a710-fc2763a3f10c.png)

2:
![image](https://user-images.githubusercontent.com/22769210/163346714-c14ae8d1-a11e-41d2-a1e5-5496b00c89a3.png)
here is where it's failing , so as to get the first connection thanks

**Comment by billywatsy** [comment]
l have seen how to set it 

http://username:password@example.com/

**Comment by dallmann-consulting** [comment]
If your are just using the simulator, you don't need an authentication. You probably have configured a username/password in the chargepoint configuration. That's why the server requires the authentiation. Just clear these fields and it should work without.
