### ISSUE TITLE
Start Transaction Error

### ISSUE THREAD

**Issue by receptanilcengiz** [dallmann-consulting/OCPP.Core#16]
Hello

I am testing server with INFINITY Simple OCPP 1.6 Chargebox Simulator provided in Readme file (https://github.com/victormunoz/OCPP-1.6-Chargebox-Simulator) 

when I click Start Transaction button it gives this error
fail: OCPPMiddleware.OCPP16[0]
      OCPPMiddleware.Receive16 => Unknown message type: 1 / Msg: [1,"ETPCN52r6YfYsB0xI2G2imfhjDf3RoUVoVe9","StartTransaction",{"connectorId":1,"idTag":"12345678","timestamp":"2022-07-10T3:11:55Z","meterStart":0,"reservationId":0}]

How can I solve this?

**Comment by billywatsy** [comment]
hi @receptanilcengiz  did you first manage to connect first ?

connect-> authorize -> start tranx ?

**Comment by receptanilcengiz** [comment]
yes I do with these orders

**Comment by dallmann-consulting** [comment]
Use a better simulator. Message type "1" is not defined in specification and therefore invalid. Normal msg types are 2/3 and 4 means error.

**Comment by Bernd81** [comment]
Hi @receptanilcengiz 
did you try to restart your Wallbox?
I had a similar issue with my Alfen Eve Single S-line wallbox. After reinitializing with a restart through management software of the box everything is working well.

**Comment by dallmann-consulting** [comment]
That one should work. Did you also try the modified one included in this repository?
Nevertheless, your error message states unknown message type "1" which is truly not allowed. 
Try different simulators and see what happens.

**Comment by dallmann-consulting** [comment]
No more activities
