### ISSUE TITLE
TLS Client Side Certificates not working on Kestrel

### ISSUE THREAD

**Issue by rhynix** [dallmann-consulting/OCPP.Core#28]
When a client tries to use a client certificate to authenticate towards `OCPP.Core.Server`, the certificate is not used by the web server. In essence, `context.Connection.ClientCertificate` in `OCPP.Core.Server/OCPPMiddleware.cs` is always empty.

The following workaround worked for me. This also disables the verification of the client side certificates as well.

```
diff --git a/OCPP.Core.Server/Program.cs b/OCPP.Core.Server/Program.cs
index 756818c..7baf813 100644
--- a/OCPP.Core.Server/Program.cs
+++ b/OCPP.Core.Server/Program.cs
@@ -22,6 +22,7 @@ using System.Collections.Generic;
 using System.Linq;
 using System.Threading.Tasks;
 using Microsoft.AspNetCore.Hosting;
+using Microsoft.AspNetCore.Server.Kestrel.Https;
 using Microsoft.EntityFrameworkCore.Metadata;
 using Microsoft.Extensions.Configuration;
 using Microsoft.Extensions.Hosting;
@@ -60,6 +61,14 @@ namespace OCPP.Core.Server
                 .ConfigureWebHostDefaults(webBuilder =>
                 {
                     webBuilder
+                    .ConfigureKestrel(kestrel => {
+                        kestrel.ConfigureHttpsDefaults(https => {
+                            https.ClientCertificateMode = ClientCertificateMode.AllowCertificate;
+                            https.ClientCertificateValidation = (cert, chain, policyErrors) => {
+                                return true;
+                            };
+                        });
+                    })
                     .ConfigureLogging((ctx, builder) =>
                                         {
                                             builder.AddConfiguration(ctx.Configuration.GetSection("Logging"));
```

**Comment by dallmann-consulting** [comment]
Hi Rik,

I guess you are using your own CA or even self signed certificates. The web server or the system don't know and don't trust these certificates. So the client certificate is rejected and the "ClientCertficate" property is empty.
With your code you are basically turning off this verification and the web server accepts **any** client certificate. For testing purposes this is no problem but in production environments this is critical. A client certificate is supposed to prove your ID - like a password - and accepting any certificate is like accepting **any** password. 

When you use a public CA or your own CA with correctly trusted root certificates the client certificate should show up in the property.

**Comment by rhynix** [comment]
Hi! Thanks for your response.

It is correct I am using a Certificate Authority that is not any of the well known trusted CAs. This explains why the certificates were not used by default.

Is there any documentation available on how to use a custom CA in OCPP.Core, or can this only be done by trusting the CA at the OS level?

I am aware that the provided code accepts any certificate from any authority.

**Comment by dallmann-consulting** [comment]
By default that's the decision of the OS.
But the function you have added gets thee parameters: cert, chain, policyErrors
It's up to you to check these values and decide whether you trust it (and return true) or not.

I would recommend configuring it on the OS level. Then you can check connections with a browser and it makes things easier.

**Comment by rhynix** [comment]
Thanks for the explanation! :+1:
