### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by LauGui2023** [dallmann-consulting/OCPP.Core#30]
I am unable to connect to the database using SQLite or SqlServer...

With SQLite, I always get this error:

An error occurred while processing your request.
Error details:
SQLite Error 1: 'no such table: ConnectorStatusView'.

What can I do?

**Comment by dallmann-consulting** [comment]
You can't use an empty database. The project contains SQL scripts to create all tables and views.
For SQLlite you can use the included empty (but prepared!) database file. But you need to adjust the file name - see config files.

**Comment by LauGui2023** [comment]
Oh yeap! I was able to prepare the database using
`sqlite3 OCPP.Core.sqlite -init OCPP.Core.sqlite.sql`

Now it works!
