### ISSUE TITLE
Error details

### ISSUE THREAD

**Issue by WesleyWu001** [dallmann-consulting/OCPP.Core#39]
Hello, we followed the normal process and steps, but when we opened the [http://localhost:8082/](url) ,we saw these error messages displayed on the webpage. Could you please advise on how to resolve this? 
![Error details](https://github.com/dallmann-consulting/OCPP.Core/assets/133877171/612ae808-f0b9-426f-949c-8eb9e87c2f7e)

**Comment by dallmann-consulting** [comment]
You configured OCPP.Core to use a SQL-Server but the connection fails. Please check your configuration.
If you don't want to install and use SQL-Server you can use SqlLite (file based database).

**Comment by WesleyWu001** [comment]
Thank you very much. We downloaded SQL-Server according to your suggestion, but now a new problem has arisen. How should we solve it?
![transient failure](https://github.com/dallmann-consulting/OCPP.Core/assets/133877171/a83d6bdb-257a-41c0-9d72-7668bfeb5380)

**Comment by dallmann-consulting** [comment]
There ist still something wrong with the database. Did you create the database with the script and can connect with SQL Management Studio?  It is not enough just to install the SQL Server.
It's probably easier to start with SqlLite. Just use the preconfigured file.

**Comment by dallmann-consulting** [comment]
Does it work now?

**Comment by WesleyWu001** [comment]
Sorry for the late reply, we have successfully run the ocpp.core and tried to connect to the charge point. If there are any problems, we will report back. Thank you.
