### ISSUE TITLE
Can't connect to the charge ponit 

### ISSUE THREAD

**Issue by FAL7029** [dallmann-consulting/OCPP.Core#42]
“I have successfully entered OCPP.CORE according to the established process. We are trying to connect to Phihong’s charge point  named "AXSC111001". Could you please tell me if we need to change the URL or other code to connect?”

**Comment by dallmann-consulting** [comment]
If the charger supports OCPP 1.6 JSON it should work without modifications. But I don't know the charger and can't help you with that.
