### ISSUE TITLE
Add implementation for SetChargingProfile

### ISSUE THREAD

**Issue by pbonato** [dallmann-consulting/OCPP.Core#46]
Is possible to have the SetChargingProfile implemented ?
I need to change the MaxCurrent for the Wallbox so I can monitor the load and balance the power for charging the EV

**Comment by dallmann-consulting** [comment]
I'm thinking about it. The limiting factor is not enough spare time.
The message itself is probably not enough. You also need an API to control the limit dynamically, right?
I thought of an MQTT interface for monitoring all activities and probably controlling the power limit.

**Comment by andreasringdal** [comment]
@dallmann-consulting What are your thought on MQTT interface for this project. 
I am looking into modifying the OCPPMiddlweare to forward all incomming messages to IOT-Hub in order to enable individual billing for the charge points.

**Comment by dallmann-consulting** [comment]
I have just added the SetChargingProfile and ClearChargingProfile messages. 
See the new Server-API.md for documentation.
Both messages are **NOT TESTED** yet!
