### ISSUE TITLE
Help Needed: Connecting Siemens VersiCharge AC Charger to Server on Same Wi-Fi Network

### ISSUE THREAD

**Issue by chalonet** [dallmann-consulting/OCPP.Core#49]
I need to connect a real Siemens charger, the VersiCharge AC. It's connected to the same Wi-Fi network as the server. Can you explain how I should do it?

**Comment by davidtomas98** [comment]
I have connected the charger to the Wi-Fi network, configured a user tag, and created the charger within the server along with the ID of the tag that had been enabled for the charger. However, when I pass the tag and unlock the charger to charge, it does not show as connected on the web page

**Comment by davidtomas98** [comment]
I have to configure something on the charger besides the Wi-Fi connection?

**Comment by dallmann-consulting** [comment]
You need to configure the URL of your server in your charger. It is basically the same like with the simulator. It is not enough just to use the same wifi connection/network.
From googling it seems that Siemens doesn't allow you to configure that yourself:
https://monta.com/uk/help-center/siemens-versicharge-installation-guide/

They state that you need to contact the support and they reconfigure your charger - probably via their cloud connection.

**Comment by davidtomas98** [comment]
You should send an email to support requesting the change to this address if the server is hosted locally: ws://localhost:9019/OCPP/{charger_id}. Once they confirm the change, I will need to create the charger and its tags within the database, similar to what I would do in the simulator. Finally, I will pass the admin tag to the charger to add user tags. When a user tag is passed, will it connect?

**Comment by davidtomas98** [comment]
I would have to send an email to support requesting the change to this address if the server is hosted locally: ws://localhost:9019/OCPP/{charger_id}. Once they confirm the change, I will need to create the charger and its tags within the database, similar to what I would do in the simulator. Finally, I will assign the admin tag to the charger to add user tags. When a user tag is passed, will it connect?

**Comment by davidtomas98** [comment]
And also, another thing please, I've noticed that the charger only accepts WSS connections. Would I need to change something in the code?

**Comment by dallmann-consulting** [comment]
"localhost" means the same computer which would be the charger. That's wrong. Please try to setup the server and simulator on different machines, You need an IP address or DNS name in your network.
WS vs. WS**S** is the same like http and http**s**. Your server (OCPP.Core server) needs an SSL certificate for https connections. Please ask Siemens if this is really necessary. If you are working in a private network this seems not really necessary.

**Comment by davidtomas98** [comment]
Now I've been told that they have set this up: ws://desktop-8f4o9rj:9019/OCPP and GROUPNAME: ALDROVE. Now, to test the functionality, I'll have to create the charger with its ID and put the ID of a tag, and theoretically it should work? I don't understand why they asked me for the GROUPNAME.

**Comment by davidtomas98** [comment]
desktop-8f4o9rj" is the name of the local server where I have the database.

**Comment by davidtomas98** [comment]
I've seen what the target group is. How do I specify the target group to OCPP on the charger, or is it unnecessary?

**Comment by davidtomas98** [comment]
![Captura](https://github.com/dallmann-consulting/OCPP.Core/assets/23049415/95e059f6-2db5-48bb-82b6-c09a1e5416a9)

**Comment by davidtomas98** [comment]
![image](https://github.com/dallmann-consulting/OCPP.Core/assets/23049415/f7f478bf-701a-4b63-a4b5-70e24d96a55e)

On the OCPP server, I have the following table of tags, and I've added two Siemens cards to the Aldrove group. However, when I swipe the card through the charger, it doesn't unlock to start the charging. What could be happening?

**Comment by davidtomas98** [comment]
They have already changed my WebSocket address and they have set it to my OCPP server's address, where I have the database, which is this: ws://DESKTOP-8F4O9RJ:9019/OCPP. I have also added the charger with its ID to the database, as well as the tags, as I have shown you. However, I don't understand why it's not working.

**Comment by dallmann-consulting** [comment]
Please check the message dump. All incoming and outgoing messages are written there as files (with default configuration). Are there any files? If not, the communication does not work. You can also check the log files on the server. You should see requests and processing information there.
If you see activity:  clear the dump directory and then present your card to the charger. You should see an authorization request and the answer from the server.

**Comment by davidtomas98** [comment]
Please, I'm new to all this, could you be more specific? Where can I check the message dumping route? How could I check the log files on the server, and how do I delete the dump directory? I'm using SQL Server Management Studio 2022.

**Comment by davidtomas98** [comment]
The charger I have is the Siemens VersiCharge AC model. To activate a card, you need to swipe the administrator card first, then the user card, and then again the administrator card. Do I need to do the same in this case if now the OCPP points to my server, and I have created the card within the database?

**Comment by davidtomas98** [comment]
I've already checked the 'messagelog' table on the server, and there are no records of communication between the charger and the server. One point I need to mention is that I have both admin and user cards, and the charger manual instructs me to swipe the admin card to set up a user card. I've done this, so when I try the user card, it beeps but doesn't unlock, and there are no entries in the 'messagelog' table.

**Comment by davidtomas98** [comment]
In the messagedump, I see this, but I don't know which charge point it is : [2,"ugXrsAnO10NtdcXFjHFZArBg81N9vacOsyUS","BootNotification",{"chargePointVendor":"AVT-Company","chargePointModel":"AVT-Express","chargePointSerialNumber":"avt.001.13.1","chargeBoxSerialNumber":"avt.001.13.1.01","firmwareVersion":"0.9.87","iccid":"","imsi":"","meterType":"AVT NQC-ACDC","meterSerialNumber":"avt.001.13.1.01"}]

**Comment by davidtomas98** [comment]
I'm trying to run the simulator on another machine within the same network, but it doesn't interact at all. I'm typing this: ws://192.168.2.221:9019/OCPP/12 where the IP is that of the server, and I've already verified that it responds to ping and connects.

**Comment by davidtomas98** [comment]
![WhatsApp Image 2024-04-19 at 09 46 49](https://github.com/dallmann-consulting/OCPP.Core/assets/23049415/ddad1672-55d3-4d94-a13e-268a65545ee5)
From the other machine, I check the connection to the server and see that it is open. However, when I enter the URL in the simulator and set it correctly, I click on 'Connect' and nothing happens.

**Comment by chalonet** [comment]
If I manage to solve the issue, I will talk to the Siemens guys and tell them to use the WS URL and put the IP instead of the server name, then everything should work perfectly. Thank you very much for responding and for the help.

**Comment by chalonet** [comment]
Yes, I managed to solve the problem. I spoke with the Siemens team and told them to change the WS URL and use the IP instead of the server name. Then everything worked perfectly. Thank you very much for responding and for the help.
