### ISSUE TITLE
Cannot find the object "Transactions"

### ISSUE THREAD

**Issue by SayedaliSayedb** [dallmann-consulting/OCPP.Core#71]
Hello Dear
I have problem to run this project 
This error massage occurs during migration
Thank you for guiding me

Microsoft.Data.SqlClient.SqlException: 'Cannot find the object "Transactions" because it does not exist or you do not have permissions.

![Screenshot 2024-09-21 102607](https://github.com/user-attachments/assets/af607b37-933f-4115-8705-67a26491c749)

**Comment by dallmann-consulting** [comment]
Is it possible that you have an empty database?
The server doesn't create the tables etc, itself. See the Script "Create_OCPP.Core.sql" in the "SQL-Server" directory.
Also make sure that the connection string points to the correct database.

**Comment by JeremyMahieu** [comment]
This is why the first migration should be to create the database but it's like this historically.

**Comment by SayedaliSayedb** [comment]
Thank you for your reply

I have tested this project on my computer.

Do I need to migration or do something before the implementation of the project?
Is it possible to guide step by step what should be done before the implementation of the project?

I followed the previous error like this, but it did not open
After running, I saw that the database was created but there was no table called Transactions, I created it myself in the database and put two values ​​"ChargePointId", "ConnectorId" and the ocpp.core.server project was executed and did not give an error.
But the ocpp.core.managment project is facing an error

![table](https://github.com/user-attachments/assets/32972384-97b9-4585-a2d3-68e7e75b97fd)
![error1](https://github.com/user-attachments/assets/abcfc9af-4ef2-4c2b-8832-66912963a485)

**Comment by JeremyMahieu** [comment]
Don't create it yourself. That is just one table of many. Upon first startup it should have run "Create_OCPP.Core.sql" which it seems like it didn't.

**Comment by SayedaliSayedb** [comment]
Yes, you are right

I completely deleted the database and rebuilt it, then I ran Create_OCPP.Core.sql and it created the tables, then I ran the project and this problem has occurred.

![table2](https://github.com/user-attachments/assets/7495a984-b2a3-4036-b182-d9d4fa0c388a)
![erorr 3](https://github.com/user-attachments/assets/3b26d1c1-22ac-44ae-bbb2-3b2b3379a5fe)

**Comment by JeremyMahieu** [comment]
Seems like you deleted the migration history table but not the transactions table, so it tried to create the index twice. Or it's something else.

**Comment by SayedaliSayedb** [comment]
I acted like this
1- I deleted the previous database OCPP.Core
2- I created a new OCPP.Core database
3- I ran the Create_OCPP.Core.sql file and saw that it created the tables
4- I ran the ocpp.core.server project
 I encountered this error

Do I need to do anything else?

**Comment by JeremyMahieu** [comment]
It seems that index is in both the migration and the initial sql file. This is not ok, not your fault.

You can temporarily fix it by editing the migration history table yourself and add "20240405204318_TransactionsIndex" version "8.0.3". Then it won't try to do the migration again and start up propertly.

**Comment by SayedaliSayedb** [comment]
I didn't understand what you meant
Is it possible to guide me on what changes should I make in the file "20240405204318_TransactionsIndex"?

**Comment by SayedaliSayedb** [comment]
Thanks for your tips
The OCPP.Core.Server project was executed
![ok](https://github.com/user-attachments/assets/37e7b291-7d12-41ef-a0c4-0c28cda8e979)
