### ISSUE TITLE
can't connected to EVcharger

### ISSUE THREAD

**Issue by SayedaliSayedb** [dallmann-consulting/OCPP.Core#74]
How can I connect the charger device to this project?

![Screenshot_20240924_150705_Gallery](https://github.com/user-attachments/assets/cc73318f-fe32-42aa-8f0c-14c4da6725f9)

![Screenshot_20240924_150654_Gallery](https://github.com/user-attachments/assets/6874a9c2-30ae-44d5-99f9-59a7b633765d)

![Screenshot_20240924_150228_Firefox](https://github.com/user-attachments/assets/ef5182f2-dba0-4b41-ba2f-8b4d2f1502f3)

**Comment by SayedaliSayedb** [comment]
no this charger supported ocpp 1.6 and ocpp 2.0 and i can set model ocpp

**Comment by dallmann-consulting** [comment]
The screenshots above don't say anything about OCPP. Maybe in "Communication settings"?

**Comment by SayedaliSayedb** [comment]
in Communication settings we can set model OCPP (1.6 or 2 or other model)
we can set 

1-Remote Ip
2-Port Number
3-Mac Address

(in serial number setting) 
4-Server DominName
5-PileSerial Number

How We Can Set Root (eg 192.168.1.8/OCPP/model3)
How We can Set ID(model3) in this Device

**Comment by JeremyMahieu** [comment]
I don't think remote IP means the public IP, maybe it's the IP of the OCPP server. But ye how are we supposed to figure out what the settings of this chinese charging point are? You didn't even show screenshots of all screens. Read the manual of your charging point, I'm sure it's well written.

**Comment by SayedaliSayedb** [comment]
I have checked different parts
But apart from these two items, I did not find any other item on the page
Would it be possible to advise what the settings are like on other devices and what I should be looking for?

**Comment by SayedaliSayedb** [comment]
How are the settings on other devices?

**Comment by dallmann-consulting** [comment]
Please ask the maker of this charger. For other chargers you can find manuals in the internet.
